### ISSUE TITLE
custom classifier?

### ISSUE THREAD

**Issue by vjjan91** [birdnet-team/birdnetR#13]
Hi @fegue,

Thanks so much for this package!
I was wondering if there is an option to train a custom classifier? I want to work with primate calls and I wonder how you go about it using R?

**Comment by fegue** [comment]
Hey @vjjan91,

There is no such option yet. `birdnetR` and the upstream `birdnet` python package are still in their early stages of development, and you can expect to see new features being implemented in the near future. Because we know that custom classifiers are important to many people, this will hopefully land sooner rather than later.

**Comment by kahst** [comment]
Quick update: The `birdnet` Python package now supports custom classifiers, so I believe we can add this to the R package.

**Comment by fegue** [comment]
work is underway :)
#17

**Comment by vjjan91** [comment]
Thank you! Excited to test it!
